// This file is auto-generated by @hey-api/openapi-ts

export type GenericError = {
    error: string;
};

export type Quiz = {
    id: string;
    question: string;
    choice: Array<(string)>;
    answerIdx: number;
};

export type User = {
    id: string;
    email: string;
    fullName: (string) | null;
    password: string;
    createdAt: (string);
    updatedAt: (string);
};

export type ValidationError = {
    formErrors: Array<(string)>;
    fieldErrors: {
        [key: string]: Array<(string)>;
    };
};

export type GetHealthStatusResponse = ({
    message?: string;
});

export type GetHealthStatusError = ((GenericError | ValidationError) | GenericError);

export type RegisterData = {
    body: {
        email: string;
        fullName?: (string) | null;
        password: string;
    };
};

export type RegisterResponse = (unknown);

export type RegisterError = ((GenericError | ValidationError) | GenericError);

export type LoginData = {
    body: {
        email: string;
        password: string;
    };
};

export type LoginResponse = (unknown);

export type LoginError = ((GenericError | ValidationError) | GenericError);

export type LogoutResponse = (unknown);

export type LogoutError = ((GenericError | ValidationError) | GenericError);

export type SelfResponse = (User);

export type SelfError = (GenericError);

export type UpdateUserData = {
    body?: {
        email: string;
        fullName?: string;
        password?: string;
        currentPassword?: string;
    };
};

export type UpdateUserResponse = (User);

export type UpdateUserError = ((GenericError | ValidationError) | GenericError);

export type GetQuizResponse = (Array<Quiz>);

export type GetQuizError = (GenericError);